spring:
  datasource:
    url: jdbc:h2:mem:stockdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password # É recomendável definir uma senha, mesmo que simples
  h2:
    console:
      enabled: true
      path: /h2-console